Moved functions around and improved checking for a profile under different conditions

diff --git a/aws-auth/aws-auth b/aws-auth/aws-auth
--- a/aws-auth/aws-auth
+++ b/aws-auth/aws-auth
@@ -3,50 +3,137 @@
 # Authenticate for aws-cli
 #
 
-AWS_CLI="aws"
-VERSION=0.1
-MFA_ROLE=
-PROFILE=
-IAM_USER=
-TOKEN=
-DURATION=129600
-OVERRIDE_PROFILE=0
-DEFAULT_PROFILE="default"
-PREFLIGHT_EXIT_CHECKS=0
+###          
+## Functions 
+#          
 
+###
+## Validate profile
+#
 function checkProfile() {
     local AWS_PROFILE=$1
     local PROFILE=$2
-    # echo "Checking profile"
-    # does profile exist and not empty? 
+    
+    # S  = Set
+    # S! = Not Set
+    # +  = Not Empty
+    # -  = Empty
+    #
+    # 1 = AWS       ENV
+    # 2 = Profile   -p
+    # 3 = Default   !
+
+    #==============================
+    #  Var set  |  Empty?   | Pro |
+    #  1  |  2  |  1  |  2  |  =  |
+    #==============================
+    #  S  |  S  |  +  |  +  |  2  | X
+    #  S  |  S  |  -  |  +  |  2  | X
+    #  S  |  S  |  +  |  -  |  1  | X error pick up other opt
+    #  S  |  S  |  -  |  -  |  3  | X
+    #  S  |  S! |  +  |     |  1  | X
+    #  S  |  S! |  -  |     |  3  | X
+    #  S! |  S  |     |  +  |  2  | 
+    #  S! |  S  |     |  -  |  3  |
+    #  S! |  S! |     |     |  3  |
+    #==============================
+
     if [ $AWS_PROFILE ]; then
-        # AWS_PROFILE is set.
-        # echo "\$AWS_PROFILE set"
-        if [ -z "$AWS_PROFILE" ] && [ -z "$PROFILE" ]; then
-            # echo "\$AWS_PROFILE empty"
-            # echo "\$PROFILE empty"
-            echo "$DEFAULT_PROFILE"
-            exit 12
+        if [ $PROFILE ]; then
+            if [ -z "$AWS_PROFILE" ] && [ -z "$PROFILE" ]; then
+                echo "$DEFAULT_PROFILE"
+                exit 12
+            fi
+            if [ -z "$AWS_PROFILE" ] && [ ! -z "$PROFILE" ]; then
+                echo "$AWS_PROFILE"
+                exit 0
+            fi
+            if [ ! -z "$PROFILE" ]; then
+                echo "$PROFILE"
+                exit 0
+            fi
+        else 
+            if [ ! -z "$AWS_PROFILE" ]; then
+                echo "$AWS_PROFILE"
+                exit 0
+            else
+                echo "$DEFAULT_PROFILE"
+                exit 0
+            fi
         fi
-    elif [ -z "$PROFILE" ]; then
-        # echo "\$AWS_PROFILE not set"
-        # AWS_PROFILE is not set.
-        # echo "\$PROFILE empty"
+    else
+        if [ $PROFILE ]; then
+            if [ ! -z "$PROFILE" ]; then
+                echo "$PROFILE"
+                exit 0
+            else
+                echo "$DEFAULT_PROFILE"
+                exit 0
+            fi
+        else
+            echo "$DEFAULT_PROFILE"
+            exit 0
+        fi
+
+        # AWS_PROFILE is not set AND PROFILE empty
         echo "$DEFAULT_PROFILE"
         exit 11
     fi
+    echo "$DEFAULT_PROFILE"
+    exit 0
 }
 
-# Pre flight checks
-# 1. is AWS installed (exit code 10)
-# 2. has a profile been set (exit code 11)
-# 2a AWS_PROFILE set
-# 2b -p supplied
-# 3. does the selected profile exist
-# 4. has the region been set
-# 5. is mfa_serial set
-# 6. is there a key and secret
+###
+## Order option, ENV, default
+#
+function findAWSCLI() {
+    if [ $OPT_AWS_CLI ]; then 
+        AWS_CLI=$OPT_AWS_CLI
+    else
+        if [[ $AWS_AUTH_CLI_PATH && ! -z $AWS_AUTH_CLI_PATH ]]; then
+            AWS_CLI=$AWS_AUTH_CLI_PATH
+        else 
+            AWS_CLI=""
+        fi
+    fi
+    AWS_CLI=`which $AWS_CLI`
+    if [ $? -ne 0 ]; then
+        printf "❌ AWS CLI is not installed; exiting\n"
+        exit 10
+    fi
+}
 
+###
+## Variables
+#
+VERSION=0.1
+
+AWS_CLI="aws"               # Default aws program name
+DEFAULT_PROFILE="default"   # Default cli profile name 
+
+PROFILE=                    # Profile supplied via options or grabbed from ENV AWS_PROFILE
+MFA_PROFILE=                # MFA profile to be created or found
+TOKEN=                      # Token from options
+
+DURATION=129600             # Duration of token
+OVERRIDE_PROFILE=0          # If profile passed in option use it
+PREFLIGHT_CHECKS=0          # Preflight error code
+
+###
+## Pre flight checks
+## 1. is AWS installed (exit code 10)
+## 2. has a profile been set (exit code 11)
+## 2a AWS_PROFILE set
+## 2b -p supplied
+## 3. does the selected profile exist
+## 4. has the region been set
+## 5. is mfa_serial set
+## 6. is there a key and secret
+#
+
+###
+## 1. Uses set options set or <token> and tries to work out which profile you want to use. 
+#
 if [ $# -gt 0 ] && [ "${1:0:1}" == "-" ]; then
     while getopts 'p:t:c:hv' OPTION
         do
@@ -75,37 +162,42 @@ if [ $# -gt 0 ] && [ "${1:0:1}" == "-" ]; then
 else
     if [ $# == 0 ]; then
         read -p 'Token ' TOKEN
-        exit 1
     else 
         TOKEN=$1
     fi
 
-    # Check $AWS_PROFILE isn't set and ""
-    # Check $PROFILE EXISTS   
-    # default / default-mfa
     PROFILE=$AWS_PROFILE
 fi 
 
-# Order option, ENV, default
-if [ $OPT_AWS_CLI ]; then 
-    AWS_CLI=$OPT_AWS_CLI
-else
-    if [[ $AWS_AUTH_CLI_PATH && ! -z $AWS_AUTH_CLI_PATH ]]; then
-        AWS_CLI=$AWS_AUTH_CLI_PATH
-    else 
-        AWS_CLI=""
-    fi
-fi
-AWS_CLI=`which $AWS_CLI`
-if [ $? -ne 0 ]; then
-    printf "❌ AWS CLI is not installed; exiting\n"
-    exit 10
-fi
+###
+## 2. Find the AWS CLI
+#
+#findAWSCLI
 
 PROFILE=$(checkProfile $AWS_PROFILE $PROFILE)
-if [[ ( $? == 11  || $? == 12 ) && ( "$PR" -eq "$DEFAULT_PROFILE" ) ]]; then
-    echo "No profile detected default set"
-fi
+# if [[ ( $? == 11  || $? == 12 ) && ( "$PR" -eq "$DEFAULT_PROFILE" ) ]]; then
+#     echo "No profile detected default set"
+# fi
+# case $? in
+#     1)
+#     ;;
+
+#     2)
+#     STATEMENTS
+#     ;;
+
+#     3)
+#     STATEMENTS
+#     ;;
+
+#     *)
+#     echo "Error"
+#     ;;
+# esac
+echo "Profile: "
+echo $PROFILE
+exit 1
+
 # unset PROFILE
 # PROFILE="$PR"
 
@@ -127,7 +219,7 @@ elif [ -z "$PROFILE" ]; then
 fi
 
 # Set the mfa profile
-MFA_ROLE="$PROFILE-mfa"
+MFA_PROFILE="$PROFILE-mfa"
 
 export AWS_PROFILE_TEMP=$AWS_PROFILE
 unset AWS_PROFILE
@@ -136,7 +228,7 @@ unset AWS_PROFILE
 EXISTS=$(aws --profile $PROFILE configure list) #>> dev/null 2>&1
 if [ $? -eq 255 ]; then
     printf "❌ Profile:\t$PROFILE isn't configured in ~/.aws/config\n"
-    PREFLIGHT_EXIT_CHECKS=1
+    PREFLIGHT_CHECKS=1
 else
     printf "✅ Profile:\t$PROFILE\n"
 fi
@@ -147,7 +239,7 @@ if [ $? -ne 0 ] || [ -z "$SERIAL_NUMBER" ]; then
     # Check mfa_serial doesn't exist
     printf "❌ MFA:\t\tAdd mfa_serial ENV to $PROFILE profile\n"
     printf "   \t\t- aws configure set mfa_serial <mfa_serial>\n"
-    PREFLIGHT_EXIT_CHECKS=1
+    PREFLIGHT_CHECKS=1
 else
     printf "✅ MFA:\t\t$SERIAL_NUMBER\n"
 fi
@@ -159,7 +251,7 @@ if [ $? -ne 0 ] || [ -z "$KEY_PRESENT" ]; then
     # Check access key doesn't exist
     printf "❌ ACCESS KEY:\tMissing aws_access_key_id\n"
     printf "   - aws configure set aws_access_key_id <key>\n"
-    PREFLIGHT_EXIT_CHECKS=1
+    PREFLIGHT_CHECKS=1
 else
     KEY_OBSCURE=${KEY_PRESENT:${#KEY_PRESENT}-3:${#KEY_PRESENT}}
     printf "✅ ACCESS KEY:\t*****************$KEY_OBSCURE\n"
@@ -171,19 +263,19 @@ if [ $? -ne 0 ] || [ -z "$SECRET_PRESENT" ]; then
     # Check secret key doesn't exist
     printf "❌ SECRET:\tMissing aws_secret_access_key\n" 
     printf "   - aws configure set aws_secret_access_key <secret>\n"
-    PREFLIGHT_EXIT_CHECKS=1
+    PREFLIGHT_CHECKS=1
 else
     SEC_OBSCURE=${SECRET_PRESENT:${#SECRET_PRESENT}-3:${#SECRET_PRESENT}}
     printf "✅ SECRET:\t*****************$SEC_OBSCURE\n"
 fi
 
-if [ $PREFLIGHT_EXIT_CHECKS == 1 ]; then
+if [ $PREFLIGHT_CHECKS == 1 ]; then
     printf "❌ Preflight:\tFailed, resolve issues above.\n"
     exit 13
 fi
 
-read AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN <<< \
-$( aws sts --profile $PROFILE get-session-token \
+read AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN <<< $( aws sts \
+    --profile $PROFILE get-session-token \
     --duration-seconds $DURATION  \
     --serial-number "$SERIAL_NUMBER" \
     --token-code $TOKEN \
@@ -194,11 +286,11 @@ if [ -z "$AWS_ACCESS_KEY_ID" ]; then
     exit 1
 fi
 
-`aws --profile "$MFA_ROLE" configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"`
-`aws --profile "$MFA_ROLE" configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"`
-`aws --profile "$MFA_ROLE" configure set aws_session_token "$AWS_SESSION_TOKEN"`
-if [ $OVERRIDE_PROFILE == 0 ] && [ "$AWS_PROFILE_TEMP" == "$MFA_ROLE" ]; then
+`aws --profile "$MFA_PROFILE" configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"`
+`aws --profile "$MFA_PROFILE" configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"`
+`aws --profile "$MFA_PROFILE" configure set aws_session_token "$AWS_SESSION_TOKEN"`
+if [ $OVERRIDE_PROFILE == 0 ] && [ "$AWS_PROFILE_TEMP" == "$MFA_PROFILE" ]; then
     printf "\$AWS_PROFILE is set, off you go :-)\n"
 else
-    printf "Set \$AWS_PROFILE to $MFA_ROLE to use 2FA account, and off you go :-).\n"
+    printf "Set \$AWS_PROFILE to $MFA_PROFILE to use 2FA account, and off you go :-).\n"
 fi
